### ISSUE TITLE
Chevron Icons

### ISSUE THREAD

**Issue by jason-beach** [tailwindlabs/heroicons#1105]
I think there is an issue with the chevron icons for the mini collection:
![image](https://github.com/tailwindlabs/heroicons/assets/11856709/453a655e-8617-4f21-bfee-c87412a2d3a5)
They seems to be off from the other variants - reporting just in case. 

Awesome work on the micro collection!

**Comment by thecrypticace** [comment]
Whoops — these got exported wrong and we missed these when looking over things. Appreciate it!

v2.1.1 is released and the website is updated.
