### ISSUE TITLE
Label all svg's with descriptive <title> tag

### ISSUE THREAD

**Issue by HonkingGoose** [tailwindlabs/heroicons#111]
## Proposed change:

- Label main `<svg>` tags with a `<title>` tag, with a descriptive text of the icon.

## Why make this change:

This change would help vision impaired users, by providing a descriptive text for the main icons.
That way, vision impaired users get the same information as fully sighted users.

Adding this title tag within the SVG also promotes a more accessible web for the developers who are using the icons on their website.

If this is something that you want, I'll go label all the svgs, and make a pull request that closes this issue. :wink: 

## Reference:

From https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title:
> The <title> element provides an accessible, short-text description of any SVG container element or graphics element.

**Comment by HonkingGoose** [comment]
Closing this issue, as adding labels is likely to hinder rather than help screen reader users.

From a screen reader user at https://github.com/tailwindlabs/heroicons.com/pull/11#pullrequestreview-475830207:
>As an occasional user of a screenreader, I’d suggest not adding this. Unlike images, svg titles are optional, and in this case adding them would just add more noise to the page, rather than providing any useful information.

**Comment by colinbes** [comment]
I'd say that having a hover title on icons should be pretty standard as the icons are not there just to be pretty but indicate function. I am surprised it's not available and feel it's an oversight

**Comment by zhe** [comment]
What @igitur mentioned is exactly what I'd like to achieve. It would be great to give users a descriptive tooltip for icons, something like `alt` for images. 

For example, `trending-up` and `trending-down` icons can be given `title`s like "Credit" and  "Debit" in a finance app.

**Comment by gflujan** [comment]
> Closing this issue, as adding labels is likely to hinder rather than help screen reader users.
> 
> From a screen reader user at [tailwindlabs/heroicons.com#11 (review)](https://github.com/tailwindlabs/heroicons.com/pull/11#pullrequestreview-475830207):
> 
> > As an occasional user of a screenreader, I’d suggest not adding this. Unlike images, svg titles are optional, and in this case adding them would just add more noise to the page, rather than providing any useful information.

Going solely off of the context of this post, if the decision to not add this feature is being decided solely because of one occasional user, I'd have to argue that the option to add `<title>`s should be available by default and it should be up to the developer(s) to choose whether to add it or not. 

If I then build something with `<title>`s and then my end users complain about it, it's up to me to decide about removing it or not.

**Comment by mtomov** [comment]
Yeah, I the arguments for having _the ability_ to do that are rather solid. I was also expecting to be able to set a title attribute to an icon, so I can then grab it with my testing tool and click on it.
