### ISSUE TITLE
check-circle has wrong svg info

### ISSUE THREAD

**Issue by damidina** [tailwindlabs/heroicons#113]
Haven't tested the jsx but the svg is not the intended icon
![Screen Shot 2020-08-27 at 4 51 00 PM](https://user-images.githubusercontent.com/2275314/91493538-7d609f00-e885-11ea-9f63-a13fb8fccd89.png)

**Comment by jsmith** [comment]
I noticed this issue and looked at the [check-circle outline](https://github.com/tailwindlabs/heroicons/blob/master/src/outline/check-circle.svg) icon but everything looks fine? I also looked at heroicons.dev and rendered it locally. How do I reproduce?

**Comment by damidina** [comment]
@jsmith looks like when I copy and paste the SVG code into figma this is what happens

**Comment by adamwathan** [comment]
This is just an issue with importing optimized SVGs into Figma I’m afraid. You can grab the Figma version from heroicons.com if you need them, will work better 👍🏻

**Comment by damidina** [comment]
@adamwathan makes sense!
