### ISSUE TITLE
Please include the license file in the NPM package

### ISSUE THREAD

**Issue by mitar** [tailwindlabs/heroicons#1139]
The package is MIT licensed, but the NPM package is missing a copy of the license. As such it is hard to satisfy MIT license conditions which require from me to include a copyright notice (which is otherwise found in the license file) as I am using the installed NPM package files and not the source code itself to search for the license file.

I think this should be as simple as adding `LICENSE` to the `files` list in `package.json`.

**Comment by mitar** [comment]
Thanks!

**Comment by reinink** [comment]
Hey, no problem, we normally include the license file with our published packages, so this must have just been an oversight. I've added it to all three packages and have published new releases 👍
