### ISSUE TITLE
Confusion about `*-small` icons deprecation

### ISSUE THREAD

**Issue by fturmel** [tailwindlabs/heroicons#1162]
I'm using the 20/solid ArrowSmallDownIcon and ArrowSmallUpIcon in an app, and the React components are now marked as deprecated with not much insight.

![CleanShot 2024-04-19 at 08 28 45@2x](https://github.com/tailwindlabs/heroicons/assets/4009209/d035c9ff-dbd8-45b2-b719-13826f1813e7)

The v2.1.0 release notes instruct to use the "mini" set instead, but I can't find references to this set in the published package. The docs page for the "mini" set just seems to be an alias to 20/solid, which is already what I am importing from.
https://github.com/tailwindlabs/heroicons/releases/tag/v2.1.0
https://unpkg.com/browse/@heroicons/react@2.1.3/
https://heroicons.com/mini

Then I thought that maybe the 20/solid standard icons would simply be equivalent to the deprecated small icons... but they are not.

![CleanShot 2024-04-19 at 09 01 29@2x](https://github.com/tailwindlabs/heroicons/assets/4009209/14d9590a-d7a7-474f-9756-ffb19d764837)

Related unanswered discussion: #1149 

Would greatly appreciate some clarifications. Will these small variants just be removed at some point and we should adapt to the 20/solid standard icons as the path forward? Is it possible to add details with the `@deprecated` jsdocs in the components?

Thanks for the great work!

EDIT: Am I just being an idiot here and simply need to downgrade to the smaller set? 24 small → 20, 20 small → 16?

**Comment by thecrypticace** [comment]
Yeah the small icons in the 24px set (solid or outline) should be replaced with the normal versions in the 20px set. Likewise, the small icons in the 20px set (mini) should be replaced with the normal versions in the 16px set (micro).

I think the idea is that we'll remove these in some later release (my guess would be v3.0 whenever that happens)

I'll look at adding a description to the deprecations 👍
