### ISSUE TITLE
Icons not available

### ISSUE THREAD

**Issue by KiranR-max** [tailwindlabs/heroicons#1198]
### Discussed in https://github.com/tailwindlabs/heroicons/discussions/1197

<div type='discussions-op-text'>

<sup>Originally posted by **KiranR-max** June 28, 2024</sup>
- Laptop icons are not available and some accessories icons needs to be added </div>

**Comment by adamwathan** [comment]
Hey thanks for the suggestions! Going to close this as we reserve issues exclusively for bugs but will keep these ideas in mind for potential future updates.
