### ISSUE TITLE
Photograph icon is not correct on Figma

### ISSUE THREAD

**Issue by micheleivani** [tailwindlabs/heroicons#126]
Thank you for the amazing icon set! 

If copy the SVG photograph icon from the _Medium_ column and paste it directly into the Figma Windows app the result is not correct. 

![image](https://user-images.githubusercontent.com/790928/92476685-a6ffbb80-f1df-11ea-9b9a-42f87b2af29d.png)

Any ideas? 

Thank you

**Comment by zaydek** [comment]
I think because the SVGs are optimized, Figma has a hard time processing them. I cleaned them up myself in this hosted version of the icons here: https://www.figma.com/file/vfjBXrSSOCgmVEX5fdvV4L/heroicons.dev-%E2%80%93-0.4.x?node-id=13944%3A312.

Best of luck!

**Comment by adamwathan** [comment]
Hey! Best to grab stuff directly from the Figma file if importing into Figma, unfortunately importing the optimized SVGs often has weird issues like this:

https://www.figma.com/community/file/958423903283802665/heroiconsZ

Thanks!
