### ISSUE TITLE
Icons are broken in Sketch

### ISSUE THREAD

**Issue by RobertCordes** [tailwindlabs/heroicons#132]
I have yet to find an icon that works when pasting it into Sketch. Everything works great in the browser, but this is how it looks in Sketch:

![broken-svgs](https://user-images.githubusercontent.com/796002/93778442-32d50700-fc26-11ea-94bf-ae086877fa9a.png)

I have just copied the first three icons as an example, but this happened with every icon I have used so far. Anybody else who has this problem?

**Comment by allaboutseb** [comment]
Steve, would love to use these, but facing the same issue here.

Mono icons which uses a similar concept of "copy svg" works without any issues.
See: https://icons.mono.company/

**Comment by huseyinemanet** [comment]
When copying these icons from Figma to Sketch, by copying SVG code and paste it to Sketch, there's no problem. But if you copy the `.svg` file directly, facing the same issue here.

**Comment by molfar** [comment]
I think icons are broken because of SVG optimization, which changes the format of d="" path attr.

**Comment by adamwathan** [comment]
Yeah unfortunately this is just the nature of importing optimized SVGs into design tools. No plans to prioritize trying to figure out a way to both optimize the SVGs while still importing correctly into Sketch I'm afraid as we don't use Sketch ourselves and we have a separate Figma version of the icons for when we need them for designing.

**Comment by RobertCordes** [comment]
Alright, fair enough.
