### ISSUE TITLE
Discount/sale icon

### ISSUE THREAD

**Issue by kendallshain** [tailwindlabs/heroicons#136]
Would be nice to have. 

Something along the lines of this: 
![image](https://user-images.githubusercontent.com/36544718/93932943-c6b1dc00-fcd5-11ea-8f46-099025da4798.png)

**Comment by rbluethl** [comment]
There is an icon called "tag", which is probably what you're looking for.
Go to https://heroicons.com/ and search for "tag".

**Comment by kendallshain** [comment]
Awesome! Thanks :)
