### ISSUE TITLE
Video call & Missed Call

### ISSUE THREAD

**Issue by bharatribadiya** [tailwindlabs/heroicons#14]
Please add
Video call
Missed Video Call
Incoming Video Call
Outgoing Video Call

**Comment by bharatribadiya** [comment]
hi...
Please add this icons

**Comment by sschoger** [comment]
Added these but I think I misunderstood the request after reading the comment.

![image](https://user-images.githubusercontent.com/2652515/89565531-b65ca500-d7ec-11ea-92cd-41e521f58373.png)

Can you please make individual GitHub issues for each of these. Going to close this issue for now and will revisit the designs for a later release when they are in new GitHub issues 🤙
