### ISSUE TITLE
[Icon Request] Double Check

### ISSUE THREAD

**Issue by ps73** [tailwindlabs/heroicons#146]
A double check icon for indicating read / received status like in whatsapp...
![WhatsAppIcon](https://user-images.githubusercontent.com/17291660/95470339-f7a23a00-0980-11eb-9c8d-7c36d737b30d.png)

**Comment by kishore007k** [comment]
I would like to work on this. If this is still available @ps73 @RobinMalfait @sschoger @adamwathan
