### ISSUE TITLE
Stroke issues in figma

### ISSUE THREAD

**Issue by fayazara** [tailwindlabs/heroicons#147]
Hey there, 

The icons looks okay on web, but when we open them in Figma, they look like this.

![image](https://user-images.githubusercontent.com/15716057/96149234-b84a8f00-0f26-11eb-9672-4fbeb78a34eb.png)

**Comment by zaydek** [comment]
Hey @fayazara, try this: https://figma.com/file/vfjBXrSSOCgmVEX5fdvV4L. I cleaned them up myself for this every reason.

**Comment by zaydek** [comment]
Pretty sure the SVG optimization breaks Figma.
