### ISSUE TITLE
dots-circle-vertical

### ISSUE THREAD

**Issue by dillingham** [tailwindlabs/heroicons#153]
heroicons.com has `dots-circle-horizontal` but not `dots-circle-vertical`

I just noticed when I went to see if vertical looked better.

Tilting my head, I do like horizontal better. Just adding incase it was overlooked.

**Comment by ArielOnoriaga** [comment]
this?

`
<svg
  class="w-6 h-6"
  fill="currentColor"
  viewBox="0 0 20 20"
  xmlns="http://www.w3.org/2000/svg"
>
  <path d="M10 6a2 2 0 110-4 2 2 0 010 4zM10 12a2 2 0 110-4 2 2 0 010 4zM10 18a2 2 0 110-4 2 2 0 010 4z" />
</svg>
`

**Comment by dillingham** [comment]
@ArielOnoriaga yup!
