### ISSUE TITLE
site issue

### ISSUE THREAD

**Issue by starkfire** [tailwindlabs/heroicons#174]
![image](https://user-images.githubusercontent.com/26057339/102632353-f021bd00-4189-11eb-8911-edb309281251.png)

**Comment by samuei** [comment]
Looks like the CSS failed to load. Refreshing might fix it, otherwise you should post some info for reproduction, like what browser and OS you're using.

**Comment by adamwathan** [comment]
This is likely just a one-off glitch, seems to be working now 👍🏻

**Comment by starkfire** [comment]
I thought it's a problem since I already tried to check the site on different browsers. But anyway, it's all working now. 😁
