### ISSUE TITLE
Social Platform icons

### ISSUE THREAD

**Issue by marcofranssen** [tailwindlabs/heroicons#184]
It would  be great to have social platform icons available that can be used to link to social platforms. E.g. when building a blog or company webpage it would be great to create some nice stylish links to the companies or personal social profiles.

- [ ] Facebook
- [ ] Twitter
- [ ] LinkedIn
- [ ] Keybase
- [ ] Instagram
- [ ] Github
- [ ] Youtube
- [ ] StackOverflow
- [ ] Reddit
- [ ] 500px
- [ ] Flickr
- [ ] Unsplash
- [ ] ...

That would prevent me from including font-awesome so I can stick completely with the tailwind stack.

**Comment by dingman** [comment]
+1

**Comment by chrissuperduper** [comment]
+1

**Comment by gidea** [comment]
+1 as well ;)
