### ISSUE TITLE
[Community] We've added a ClojureScript wrapper lib for Heroicons

### ISSUE THREAD

**Issue by avocade** [tailwindlabs/heroicons#192]
If you eventually add a section to the README with links to libs for other languages, we'd be glad to be included there ☺️

https://github.com/backminds/heroicons-clojure/

**Comment by adamwathan** [comment]
Awesome thank you! 🙌🏻 Will add a section to the readme for projects like this soon 👊

**Comment by avocade** [comment]
Hey @adamwathan, that's great! However we recently moved the repo to our company Fluent, so if you could change it to the new link that would be great (the old Backminds-hosted repo is now private):

https://github.com/fluent-development/heroicons-clojure/
