### ISSUE TITLE
Double chevron

### ISSUE THREAD

**Issue by herpaderpaldent** [tailwindlabs/heroicons#20]
![image](https://user-images.githubusercontent.com/6583519/76466422-f52a3280-63e7-11ea-9fb3-dbd201b9ef40.png)

having double chevron would be helpful

**Comment by danjus10** [comment]
Hi,

I had the same query but then realised that making a double chevron is trivial once you have the markup for the first.

This is one chevron:
<path d="M15 19l-7-7 7-7"></path>

To see a double add another chevron offset from first M15 to M9 

<path d="M15 19l-7-7 7-7  **M9** 19l-7-7 7-7"></path>

![image](https://user-images.githubusercontent.com/37114016/88582681-04ccaf80-d047-11ea-98dc-1bf6496b5056.png)

Hope that helps !

**Comment by jsmith** [comment]
It's already been made and on the way! See https://twitter.com/steveschoger/status/1283144200675090433

**Comment by sschoger** [comment]
Added!
![image](https://user-images.githubusercontent.com/2652515/89565362-73023680-d7ec-11ea-8d8c-8c135a00e166.png)

**Comment by herpaderpaldent** [comment]
Thank you very much !
