### ISSUE TITLE
Update outline academic-cap.svg

### ISSUE THREAD

**Issue by hipig** [tailwindlabs/heroicons#206]
![image](https://user-images.githubusercontent.com/24596908/109441559-8159bd80-7a70-11eb-963c-62b2fee43675.png)
`academic-cap` icon should not have a white background, in dark background, it is inconsistent with other outline icon

**Comment by Linda-645** [comment]
raduation Cap Outline SVG vector file in monocolor and multicolor type for Sketch or Illustrator from Graduation Cap Outline Vectors svg vector.

**Comment by hipig** [comment]
> raduation Cap Outline SVG vector file in monocolor and multicolor type for Sketch or Illustrator from Graduation Cap Outline Vectors svg vector.
> 
> [Paycheckrecords](https://www.paycheckrecords.bid/)

Sorry, I don't understand. If I'm on a black background, I should set the stroke color to white, but the SVG background is also white. What should I do

**Comment by bradlc** [comment]
Thanks for reporting! This was fixed in #171 👍
