### ISSUE TITLE
[Feature Request 🙏] Also make components for Svelte.

### ISSUE THREAD

**Issue by verbose9** [tailwindlabs/heroicons#232]
We are eager to have components for Svelte too.

**Comment by adamwathan** [comment]
PR welcome!

**Comment by mattjennings** [comment]
I've opened PR #245 for this. If anyone's willing to try it out, feedback would be appreciated!

**Comment by adamwathan** [comment]
Hey! I know I said "PR welcome" back in April but recently it's become clear to me that we have to be really careful about what we take on and commit to maintaining, so I think this is better as a separate community-maintained package 👍🏻  Thanks and hope that's understandable.
