### ISSUE TITLE
Distribute icons as TTF

### ISSUE THREAD

**Issue by KingDoxik** [tailwindlabs/heroicons#246]
Hi, are there any plans to make it into a font form as well? I love using those icons for web, but currently porting my web app to mobile using Flutter and the SVG support is not great. Having a font would be a lifesaver. It could probably be automated using https://github.com/RomanAliyev/figma-export as well, but tbh I am not sure with that one.

**Comment by prateekmedia** [comment]
@KingDoxik or use https://github.com/tancredi/fantasticon to generate it.

**Comment by adamwathan** [comment]
Hey! No plans to distribute these as TTF ourselves but of course more than welcome to use tools like the one recommended above to build them as TTF for your own use cases, and even distribute that via npm yourself for others if you'd like. Thanks 🍻
