### ISSUE TITLE
default width / height for each icons

### ISSUE THREAD

**Issue by Sebastien-Ahkrin** [tailwindlabs/heroicons#248]
Hello there 👋 

Would it possible to add a default height / width props on every icons ?
actually, if we didn't set any height / width we have that result:
![image](https://user-images.githubusercontent.com/30870051/114852000-aa48ce80-9de2-11eb-9a98-93680cd60f14.png)

i think, 1em for width / height would be a good default so the user doesn't have to always specify a size.
With that default size, we can specify an other size too ...

For example with 1em we have this:
![image](https://user-images.githubusercontent.com/30870051/114852109-c51b4300-9de2-11eb-8a74-b063f9dd08dc.png)

**Comment by ComedyTomedy** [comment]
Hello, is this actually fixed? I can't see `width="1em" height="1em"` either in the source files or on the icon examples at heroicons.com.
