### ISSUE TITLE
Add `aria-hidden="true"` by default

### ISSUE THREAD

**Issue by neupauer** [tailwindlabs/heroicons#257]
Because icons are almost always a purely decorative element, it would be handy to mark them as `aria-hidden="true"` by default.

They can be re-exposed to `Accessibility Tree` explicitly later in code if needed ( `aria-hidden="false"` ).

**Comment by rashidul0405** [comment]
Usually, icons are linked. doesn't pass accessibility test https://dequeuniversity.com/rules/axe/4.8/link-name

**Comment by mockdeep** [comment]
You can put `aria-label` on your `a` tag to satisfy accessibility standards.

**Comment by rashidul0405** [comment]
Yep, that's always needed to do. It's fine; my thought was that buttons are not necessarily used primarily as decorative elements nowadays.
