### ISSUE TITLE
External link icon

### ISSUE THREAD

**Issue by ArielOnoriaga** [tailwindlabs/heroicons#264]
Please add external link icon

[reference](https://image.flaticon.com/icons/png/512/25/25284.png)

**Comment by quick007** [comment]
Yes please, I was in need of this today, would LOVE to see one added to heroicons

**Comment by arenasv86** [comment]
I think it already exists: It's called **external-link**

**Comment by ArielOnoriaga** [comment]
yup

`<svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M11 3a1 1 0 100 2h2.586l-6.293 6.293a1 1 0 101.414 1.414L15 6.414V9a1 1 0 102 0V4a1 1 0 00-1-1h-5z"></path><path d="M5 5a2 2 0 00-2 2v8a2 2 0 002 2h8a2 2 0 002-2v-3a1 1 0 10-2 0v3H5V7h3a1 1 0 000-2H5z"></path></svg>`

**Comment by elie222** [comment]
> yup
> 
> `<svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M11 3a1 1 0 100 2h2.586l-6.293 6.293a1 1 0 101.414 1.414L15 6.414V9a1 1 0 102 0V4a1 1 0 00-1-1h-5z"></path><path d="M5 5a2 2 0 00-2 2v8a2 2 0 002 2h8a2 2 0 002-2v-3a1 1 0 10-2 0v3H5V7h3a1 1 0 000-2H5z"></path></svg>`

It's called `external-link` for others looking for it:
https://heroicons.dev/?query=external

**Comment by joeyfigaro** [comment]
It looks like this icon was removed in v2 of heroicons, for anyone else running into this.

**Comment by quick007** [comment]
> It looks like this icon was removed in v2 of heroicons, for anyone else running into this.

It's been renamed to `arrow-top-right-on-square` (quite the mouthful). I'd recommend using the [official heroicons site](https://heroicons.com/) bc it has better searching rather than the .dv one
