### ISSUE TITLE
Attempted import error with "ArrowSmLeftIcon"

### ISSUE THREAD

**Issue by ahmedsamirdev** [tailwindlabs/heroicons#266]
I have this issue as I tried other icons as ArrowCircleRightIcon it works

but this icon ArrowSmLeftIcon

giving me msg
"Attempted import error: 'ArrowSmLeftIcon' is not exported from '@heroicons/react/outline'."

**Comment by simonswiss** [comment]
Hey!

I just tried, and the import is working properly:

https://codesandbox.io/s/crimson-lake-lnxdi8?file=/src/App.js

Going to close this issue, but if this is still a problem for you, please create another issue with a GitHub reproduction of the actual problem, so we can help troubleshoot.

Thanks!
