### ISSUE TITLE
Could not find a declaration file for module '@heroicons/vue/solid'

### ISSUE THREAD

**Issue by agorin** [tailwindlabs/heroicons#276]
Please, add support for Typescript (Vue)

**Comment by marssantoso** [comment]
Just came across this too but apparently there is a workaround for this:

https://github.com/tailwindlabs/heroicons/issues/252#issuecomment-823090230

**Comment by bartenra** [comment]
Pinging @adamwathan.

The lack of types is very annoying.

#254

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

We now ship types for both the React and Vue versions. Make sure that you are on the latest version 👍
