### ISSUE TITLE
Add React/vue component name in icon list

### ISSUE THREAD

**Issue by vousys** [tailwindlabs/heroicons#284]
Hi! I'm sending you this suggestion, that would make any new react developer's life easier.
It would be very useful if you add the name of the component (react or vue) besides the icon

![image](https://user-images.githubusercontent.com/12813221/119811202-34458600-bebd-11eb-8182-13e470b53310.png)

Because you have to figure it out what's the name of it in this  page https://unpkg.com/browse/@heroicons/react@1.0.1/outline/
Ej:  arrow-circle-down  is  ArrowCircleDownIcon

**Comment by firatkaya1** [comment]
I agree with you. I changed little things on the code and created PR. If they accept it will be beneficial for us. Especially for Reactjs and Vuejs developers.

![Screenshot from 2021-06-03 22-35-58](https://user-images.githubusercontent.com/47042445/120702282-92c1c400-c4bc-11eb-8a82-ab04ed9db38d.png)

**Comment by reinink** [comment]
Hey! Just doing some issue cleanup, and I'm going to close this issue as per Adam's comment in this PR: https://github.com/tailwindlabs/heroicons.com/pull/58#issuecomment-927104955

Thanks for sharing this either way — we'll keep this improvement in mind for future updates to the website 👍

**Comment by nkconnor** [comment]
Yeah, this would be a great feature to have. The above link no longer works to see the context.
