### ISSUE TITLE
pasting home outline svg into figma broken

### ISSUE THREAD

**Issue by zebapy** [tailwindlabs/heroicons#297]
I'm copying and pasting the SVG home outline from the website into Figma and get this result. Not sure if it's solvable in the codebase but thought I'd raise it. All other icons Ive been pasting this way have worked perfectly.

<img width="248" alt="Screen Shot 2021-06-19 at 3 07 36 PM" src="https://user-images.githubusercontent.com/2199845/122653050-1829b300-d110-11eb-97d3-ade799990cfa.png">

**Comment by adamwathan** [comment]
Hey! Yeah annoyingly some of the optimized SVGs don't import well into design tools. I would recommend just using the Figma source when using them in Figma:

https://www.figma.com/community/file/958423903283802665/heroiconsZ

Hope that helps 🍻
