### ISSUE TITLE
Can't install on React...

### ISSUE THREAD

**Issue by andrii1** [tailwindlabs/heroicons#300]
I went to my project directory, did npm install @heroicons/react, but still getting
ReferenceError: PhoneIcon is not defined

**Comment by maxbeatty** [comment]
This is working for me

```json
"dependencies": {
    "@heroicons/react": "^1.0.1",
    "react": "^17",
    "react-dom": "^17"
}
```

```jsx
import { XCircleIcon } from '@heroicons/react/solid';

<XCircleIcon className="w-5 h-5 text-red-400" aria-hidden="true" />
```

**Comment by YinHoChong** [comment]
Try to install this [package](https://www.npmjs.com/package/@heroicons/react?__cf_chl_captcha_tk__=pmd_0d68d225596235b3bae40e9b557cc5a187505939-1629189832-0-gqNtZGzNAvijcnBszQd6).

**Comment by adamwathan** [comment]
Hey! I can't reproduce this so going to close — if this is still an issue for you please open a new issue and include a reproduction and we'll better be able to help 👍🏻
