### ISSUE TITLE
Simple README.MD Fixes

### ISSUE THREAD

**Issue by TahaHaza00** [tailwindlabs/heroicons#301]
This may seem irrelevant but it saves some of us a bit of time and sometimes a lot of time if you take it into consideration of messing up. at the beginning, when you show how to install the package, you only mention npm install @heroicons/react. But to save us a bit of time (or a lot) at least add yarn add @heroicons/react or other package managers (if compatible with heroicons). Just felt the need to mention that :).

**Comment by adamwathan** [comment]
Thanks for the suggestion! Will keep it in mind if it continues to come up, in the mean time I think we're just going to stick with npm as I think most yarn users know how to translate the command. Thanks again 🍻
