### ISSUE TITLE
Add https://heroicons.dev/ to the GitHub description

### ISSUE THREAD

**Issue by vvo** [tailwindlabs/heroicons#32]
Hi there, can you add https://heroicons.dev/ to the GitHub description too? Here:
![image](https://user-images.githubusercontent.com/123822/78978016-5f361480-7b19-11ea-8481-df6f764fbbb8.png)

thanks!

**Comment by adamwathan** [comment]
Cleaning up here, closing this since it's no longer relevant. Thanks though!
