### ISSUE TITLE
Not able to install outline

### ISSUE THREAD

**Issue by Grapdevs** [tailwindlabs/heroicons#338]
**Not able to find package.json**

`vue-cli-service serve

 INFO  Starting development server...
98% after emitting CopyPlugin

 ERROR  Failed to compile with 2 errors                                                       10:11:28 PM
These dependencies were not found:

* @heroicons/vue/outline in ./src/main.js
* @heroicons/vue/solid in ./src/main.js

To install them, you can run: npm install --save @heroicons/vue/outline @heroicons/vue/solid
Terminate batch job (Y/N)? y
PS D:\RND\vue learn\my_tasks\my_task>  npm install --save @heroicons/vue/outline @heroicons/vue/solid
npm ERR! code ENOLOCAL
npm ERR! Could not install from "@heroicons\vue\outline" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Rajneesh\AppData\Roaming\npm-cache\_logs\2021-09-07T16_41_43_711Z-debug.log   
PS D:\RND\vue learn\my_tasks\my_task> `

**Comment by adamwathan** [comment]
Hey! You want to install `@heroicons/vue`, not `@heroicons/vue/outline`:

```
npm install --save @heroicons/vue
```

That's a mistake in the error message reported by vue-cli, sorry for the confusion.
