### ISSUE TITLE
Unexpected sm icon in outline dist/

### ISSUE THREAD

**Issue by matschik** [tailwindlabs/heroicons#39]
<img width="477" alt="Capture d’écran, le 2020-04-26 à 12 50 28" src="https://user-images.githubusercontent.com/34612598/80305373-987aaf80-87bc-11ea-871d-3c13ae970e6c.png">

File name highlighted in blue does not seem to be in the right place and is not necessary.

**Comment by impulse** [comment]
Actually, there is also a `md-library.svg`in the `solid-sm` folder.

**Comment by adamwathan** [comment]
Hey! Closing because I _think_ as far as I can tell this is just not relevant anymore and things are cleaned up now,  but if I'm wrong please open a new issue ❤️  Thanks!
