### ISSUE TITLE
Tag releases when new icons are added

### ISSUE THREAD

**Issue by AlexVipond** [tailwindlabs/heroicons#41]
For people maintaining Heroicons component libraries (e.g. @codex-zaydek, [and me](https://baleada.netlify.app/docs/icons/)), it's great to be able to watch the repo for releases only, not issues and comments, so that we know when to rebuild and republish.

Doesn't need to be anything fancy—no need for precise semantic versioning, or binaries being included. A bulleted list of which icons have been added would be 👌

**Comment by codex-zaydek** [comment]
Agreed! Thanks for creating an issue @AlexVipond.

**Comment by adamwathan** [comment]
Doing some tidying up — closing as this doesn't seem relevant any more now that we are tagging/publishing our own packages ❤️
