### ISSUE TITLE
md-book-open is not a valid SVG file

### ISSUE THREAD

**Issue by nthnluu** [tailwindlabs/heroicons#44]
This SVG appears to be corrupt. The file preview on Github does not work, nor does the downloaded file.

**Comment by Sinnbeck** [comment]
Take a look at this thread. There is no namespace meaning it isnt a valid svg file
https://github.com/refactoringui/heroicons/issues/40

**Comment by adamwathan** [comment]
Added namespace a while ago so going to close (although the namespace is not necessary for inline SVG which is how these are intended to be used).
