### ISSUE TITLE
Icon Request: Social Media

### ISSUE THREAD

**Issue by IsidroMar95** [tailwindlabs/heroicons#46]
I've seen that in some TWUI examples they use some social media icons, can you include them? Also linkedin and Behance

![image](https://user-images.githubusercontent.com/23019968/82480022-ce981000-9a98-11ea-8d60-403846c7004e.png)

**Comment by stoqe** [comment]
- is the source for these social icons known?

**Comment by austriker27** [comment]
Id also love to see social media icons added!

**Comment by deadcoder0904** [comment]
Here's a great alternative https://svgporn.com/

The only con with using it is you have to open SVG & change colors if you don't want to use the original logo colors which are tedious to handle. Idk much SVG so not sure if it's easy or hard.

**Comment by geekish** [comment]
https://simpleicons.org/

**Comment by dillingham** [comment]
Just came here to request these

**Comment by gidea** [comment]
Also looking forward to seeing the heroicons library expanded with social media (using tailwindUI btw, and I need the linkedin icon in the same style as the others, most likely will just self host the svg for it)
