### ISSUE TITLE
Icon Request: Document File

### ISSUE THREAD

**Issue by impulse** [tailwindlabs/heroicons#48]
Since we have `document-report` it would be nice to also have something like this to indicate a file with text content:

![out](https://user-images.githubusercontent.com/8146736/82782476-b9d2c800-9e5c-11ea-9e2a-3d3db9fe489f.png)

**Comment by sschoger** [comment]
Added!

![image](https://user-images.githubusercontent.com/2652515/89564659-54e80680-d7eb-11ea-940e-4854dbdef524.png)
