### ISSUE TITLE
Icon Request: Servers

### ISSUE THREAD

**Issue by ammmir** [tailwindlabs/heroicons#49]
I would like to request icons that depict a single server, multiple servers, and a network :)

**Comment by sschoger** [comment]
Added servers and a few options for the other requests. 

If you're still looking for something more specific for the other ones can you make a new individual GitHub issue for each please? Thanks for the requests :)

![image](https://user-images.githubusercontent.com/2652515/89564894-b3ad8000-d7eb-11ea-9c3d-28dc937b201e.png)
