### ISSUE TITLE
Minus Icon

### ISSUE THREAD

**Issue by michealjroberts** [tailwindlabs/heroicons#5]
I sound like I am moaning something rotten - but there doesn't look to be a minus sign, but a plus sign. Well worth adding.

Switching from font-awesome to heroicons for applications.

**Comment by cossssmin** [comment]
Yes please! 😊 

Was just building a mobile dropdown with a +/- icon toggle with Tailwind UI, but there's no **&ndash;** icon so I have to fallback to chevrons for now :(

**Comment by Braunson** [comment]
Also requesting, while working on an FAQ design, I noticed heroicons has a + plus icon but not a matching/complimentary minus/negative icon (there is a rounded but it does not match the non-rounded plus).
