### ISSUE TITLE
For Brand Icons, consider Directing People to Simpleicons

### ISSUE THREAD

**Issue by sasial-dev** [tailwindlabs/heroicons#507]
[Simple Icons](https://simpleicons.org/) is a website just for brand icons, and as so many people ask questions about having them you might as well just direct them there.

**Comment by adamwathan** [comment]
Hey thanks! Yeah I agree, will think on how we might link to that resource in a way that people will actually find it 🤔 In the mean time, anyone searching for brand icons in the issues will find this issue which will be helpful for them 👍🏻 

Going to close as not a bug or anything but appreciate the input and will think about the best way to apply it!
