### ISSUE TITLE
vue2 support

### ISSUE THREAD

**Issue by gustawdaniel-acaisoft** [tailwindlabs/heroicons#518]
Is planned support for vue2 or can you recommend me alternative to this package that support vue2?

**Comment by adamwathan** [comment]
Hey! Been discussed previously here: https://github.com/tailwindlabs/heroicons/pull/235#issuecomment-917407176

The icons are just SVG, can copy and paste them as needed into a Vue 2 project and wrap them up as little components if you want 👍🏻
