### ISSUE TITLE
Supertype for icons?

### ISSUE THREAD

**Issue by RobRoseKnows** [tailwindlabs/heroicons#542]
As of #64, there's now Typescript types for the icons. I was hoping though that there could be some sort of "supertype" for all the icons, so that I could define a React component that would require an icon instead of just a generic ReactNode. My usecase is I'm trying to make a generic version of [this component](https://tailwindui.com/components/marketing/sections/feature-sections#component-cdca7eda27bdaceb45026dca4c17efe7) from Tailwind UI, and it would be nice if I could make it so a generic icon could be provided.

**Comment by timroes** [comment]
Since all icons are just taking `svg`s props into them (since they are just that), you can define a type for any generic icons, like:

```ts
type Icon = React.ComponentType<React.ComponentProps<'svg'>>;
```

**Comment by RobRoseKnows** [comment]
Good point, I ended up figuring that out and forgot to close earlier. Thanks!

**Comment by eccentric-j** [comment]
It seems in a recent update that definition no longer applies. Anyone know what it should be now?

**Comment by michaelphines** [comment]
This works for me:

```jsx
export type HeroIcon = React.ComponentType<
  React.PropsWithoutRef<React.ComponentProps<"svg">> & {
    title?: string | undefined;
    titleId?: string | undefined;
  }
>;
```
