### ISSUE TITLE
Missing tags and releases

### ISSUE THREAD

**Issue by adamchainz** [tailwindlabs/heroicons#552]
The latest version is 1.0.5, but the latest tag is v1.0.3, and the latest GitHub release is v1.0.0. This is a bit confusing for those of us using the repo :)

(I repackage heroicons as a Python package: https://github.com/adamchainz/heroicons . I check for a upstream versions every couple months.)

**Comment by bradlc** [comment]
Hey @adamchainz, thanks for the heads up! The tags and releases have both been updated 👍

**Comment by adamchainz** [comment]
Brill
