### ISSUE TITLE
Cant copy JSX when copying code from site.

### ISSUE THREAD

**Issue by kritik-sah** [tailwindlabs/heroicons#559]
there are two option Copy Svg or Copy Jsx on site copy JSx is not working

**Comment by benrudolphWSP** [comment]
Same here. It just copies SVG even if you click the JSX button. I've tried on the latest release of Chrome and Edge.

**Comment by Anishpras** [comment]
Can I work on this issue?

**Comment by reinink** [comment]
Hey folks! I just left a comment on a related PR which explains how the copy feature is intended to work: https://github.com/tailwindlabs/heroicons.com/pull/93#issuecomment-1013696646

TLDR; The "Copy JSX" button provides a JSX compatible version of the SVG — the `class` attribute is converted to `className`.

Hope that helps 👍

**Comment by 2018eeb1139** [comment]
not working as of now always SVG is copied everytime. sometimes it is very irritated.

**Comment by markbolster12** [comment]
My understanding is there are React components created to use - what is the recommended way to find the name of these components, and why would we need svg compatible with JSX when the component already exists?
