### ISSUE TITLE
Add more Icons

### ISSUE THREAD

**Issue by Mrbeyond** [tailwindlabs/heroicons#576]
Please add more Icons.

**Comment by reinink** [comment]
Hey!

This is Steve's pet creative project, and he works on it as he has time. Meaning, we can't promise that new icons are going to be added.

That said, you can request new icons in the discussions section, here: https://github.com/tailwindlabs/heroicons/discussions

Further, you might be interested to know that Steve has been working on an updated icon set: https://twitter.com/steveschoger/status/1478459451061555203

Hope that helps 👍
