### ISSUE TITLE
stop.svg is invalid

### ISSUE THREAD

**Issue by garrettmaring** [tailwindlabs/heroicons#62]
Github shows this error. I'm seeing errors using it locally as well.

![Screen Shot 2020-06-04 at 2 29 31 PM](https://user-images.githubusercontent.com/8270120/83812161-e4e4c500-a66f-11ea-982c-f651ed314e98.png)

**Comment by codex-zaydek** [comment]
This appears to be true with _all icons_. Try pressing the code button to the left of the active button to get the HTML without editing the file. If you need easier access for previewing icons, I recommend heroicons.dev.

**Comment by Sinnbeck** [comment]
It is due to missing namespace
https://github.com/refactoringui/heroicons/issues/40

**Comment by adamwathan** [comment]
Closing since we added the namespace a while back 🍻
