### ISSUE TITLE
vue: Safari Version 15.5 (17613.2.7.1.8) won't show svgs due to no width or height

### ISSUE THREAD

**Issue by NorseGaud** [tailwindlabs/heroicons#707]
Hi, so we import the icons with the traditional approach: 

```
{
  SearchIcon,
} from '@heroicons/vue/outline'
```

We then see the icon showing up in the HTML, but not on the UI. 

![Screen Shot 2022-06-17 at 3 31 04 PM](https://user-images.githubusercontent.com/5896030/174390226-852987d5-13b7-4004-945d-a926d24c6d0f.png)

When I manually add an attribute on the SVG like `width="21"`, it shows properly in the UI.

I realize that setting a width and height is probably hard to do by default, but I also don't see any documentation that shows how to set this. What can be done?

**Comment by adamwathan** [comment]
Hey! You are expected to write the necessary CSS or assign a class to the icons to give them the size you want, same way you set the color:

![B0D997E2-6721-401B-BE11-A8C662CCCCD1](https://user-images.githubusercontent.com/4323180/174408020-ed616c77-804c-49dc-9c14-a7c52069931e.png)

Hope that helps!
