### ISSUE TITLE
Stroke Width gets increased when zooming in Safari Browser for React outline icons

### ISSUE THREAD

**Issue by ahmed-abdelhamid** [tailwindlabs/heroicons#710]
I have an issue that when I try to zoom in while working on Safari, the stroke width of React outline icons is scaled; that never happens with Chrome. Here is a screenshot to show my case:

This is the case when I zoom in.
<img width="89" alt="Screen Shot 2022-06-23 at 3 43 10 PM" src="https://user-images.githubusercontent.com/26855678/175301316-00eb5cb8-4680-44ff-ae59-5b537d93500e.png">

This is the case when there is no zooming.
<img width="60" alt="Screen Shot 2022-06-23 at 3 43 33 PM" src="https://user-images.githubusercontent.com/26855678/175301382-7519ca75-fef6-41c0-9ffd-2472fac28049.png">

**Comment by adamchainz** [comment]
This doesn't happen on Firefox either. It seems like a Safari bug, could you look for it on their issue tracker?

**Comment by ahmed-abdelhamid** [comment]
> This doesn't happen on Firefox either. It seems like a Safari bug, could you look for it on their issue tracker?

I am sorry but what is Safari issue tracker?

**Comment by adamchainz** [comment]
I found e.g. this bug that several tests to do with zooming SVG's have been failing for a while: https://bugs.webkit.org/show_bug.cgi?id=158928

**Comment by adamwathan** [comment]
Yeah unfortunately this seems to be a Safari issue with rendering SVG strokes when zooming, and I can reproduce this with other stroke-based SVG icon libraries like [Feather](https://feathericons.com) when zooming in Safari too:

<img width="2965" alt="image" src="https://user-images.githubusercontent.com/4323180/175816291-d55e6cd9-ef95-4d4d-b107-e94efa97cd34.png">

Unfortunately don't think there's anything we can do here ourselves to help so going to close. Hope they resolve this in a future Safari update 🤞

**Comment by bradleybensmith** [comment]
It's unfortunately 2026 and this still isn't fixed in Safari 26... 🤷‍♂️

I did find a weird workaround you can apply through CSS:

```css
svg[data-slot=icon] {
  stroke-width: 1.5;
}
```

Might be an issue if you mix outline/solid icons.
