### ISSUE TITLE
Feedback: `check` icon

### ISSUE THREAD

**Issue by jlalmes** [tailwindlabs/heroicons#736]
Just upgraded to `v2.0.0` looks great! 🎉🚀 

I suppose this is just one person's opinion, but the new `check` icon is really jarring. Should we include the old v1 style `check` icon in v2 and introduce this as a new icon in v2 ie. `swoosh`?

<img width="781" alt="Screenshot 2022-08-23 at 17 45 46" src="https://user-images.githubusercontent.com/69924001/186215058-a2e17ec0-16be-4e5e-948f-84c90acba086.png">

No hard feelings if you want to close this issue, but thought I'd share my initial thoughts. 

Again v2 looks great, looking forward to using the updated iconset!

**Comment by Soviut** [comment]
I'm in favour of a straighter checkmark, but this would also require some consideration for the other icons that have a checkmark in them.

![image](https://user-images.githubusercontent.com/226882/186328635-8a895d87-c1fa-4e66-b4ba-0057789f6385.png)

**Comment by robclancy** [comment]
I guess they are trying to make their icons have their own unique look a bit more. But that screenshot there with it beside other icons just makes the standalone one look bad.

**Comment by denjaland** [comment]
I like the new one when it's inside the other icons indeed; standalone I think I'd still prefer the straight one indeed.  Just my 0.02

**Comment by sschoger** [comment]
Went ahead and made a straight checkmark. Was going to add it as an alternative but it felt weird that the curved one would be the default and the straight one would be the alternative so it felt necessary to apply this change to all of the icons:

<img width="1184" alt="CleanShot 2022-08-24 at 15 12 52@2x" src="https://user-images.githubusercontent.com/2652515/186504065-5d7efc95-b5a0-4f60-9814-7a8dc69df741.png">

Improvement?

**Comment by Soviut** [comment]
@sschoger Personally I think it's an improvement. On standard definition screens it seems to alias less than the more rounded one.

For example

![image](https://user-images.githubusercontent.com/226882/186506303-7e10abec-6e4d-4ea7-a472-19470510d48a.png)

**Comment by denjaland** [comment]
Much better imo 👌

**Comment by jlalmes** [comment]
Looks great @sschoger - thank you!

**Comment by RobinMalfait** [comment]
Hey! Thank you for your suggestion!
Much appreciated! 🙏

This should be fixed by #762, and will is available in the next release (2.0.5).
