### ISSUE TITLE
[solid] Inconsistent naming 

### ISSUE THREAD

**Issue by JustinVoitel** [tailwindlabs/heroicons#742]
I don’t know if this is intended but in solid the `code` & `code-square` have a different name than in outline and mini (`code-bracket` & `code-bracket-square`).

**Comment by xt0rted** [comment]
I have a code generator that builds a [helper library](https://github.com/xt0rted/heroicons-tag-helper) for asp.net and these file name differences just broke it. I hope this isn't an intentional change.

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This should be fixed by #756 (and #757) and will be available in the next version which will be released soon ish!
