### ISSUE TITLE
DatabaseIcon missing from V2

### ISSUE THREAD

**Issue by chriswill** [tailwindlabs/heroicons#749]
It's not in the Figma file, so maybe it was intended to be removed.  But it was a nice icon that was just trying to do it's best.  I was using this in V1 and am sadly missing it.

**Comment by dazlygonsalves** [comment]
It Actually Exists, it's called circle-stack now
![image](https://user-images.githubusercontent.com/51431061/186336405-465cb6a2-d2ee-4c03-8a31-bfc3c59521aa.png)
