### ISSUE TITLE
Icon names are truncated

### ISSUE THREAD

**Issue by wellbrained** [tailwindlabs/heroicons#752]
The names of the icons are truncated so it makes it impossible to see the names.

Example: 
Search for `clipboard` and you find `clipboard-docume...`.

**Comment by adamwathan** [comment]
Will think through if there's a nice way to solve this in the UI but you can hover the name to get a browser native tooltip with the full name to make it easier to find the corresponding icon in the React/Vue packages:

<img width="289" alt="image" src="https://user-images.githubusercontent.com/4323180/186425096-f176e704-6377-4dcb-a172-a9b9e48e0049.png">

Going to close as not a bug with the actual library — should use the [website repo](https://github.com/tailwindlabs/heroicons.com) for stuff like this 👍🏻
