### ISSUE TITLE
currency-taka (Currency of Bangladesh)

### ISSUE THREAD

**Issue by devfaysal** [tailwindlabs/heroicons#753]
Thank you for the new refreshed icon set.
currency-taka (Currency of Bangladesh) was available in V1 (currency-bangladeshi).
It would be really nice to have it on v2 as well.

![screenshot-2022-08-24-07-44-59](https://user-images.githubusercontent.com/16212149/186299313-de4a6971-91f7-40d6-b823-da0db4e0aad3.jpg)

**Comment by sschoger** [comment]
Hey! 

Sorry I missed this one. We just pushed an update that now includes this icon 👍🏻

<img width="1204" alt="CleanShot 2022-08-30 at 11 52 24@2x" src="https://user-images.githubusercontent.com/2652515/187483499-e1a7e60c-709d-43a7-8d7b-06502f60c641.png">
