### ISSUE TITLE
`exclamation-triangle` is not properly centered

### ISSUE THREAD

**Issue by Rizky92** [tailwindlabs/heroicons#774]
Hi,

Upon the release of v2, the icon `exclamation-triangle` is noticably off-centered when compared to v1 `exclamation`. I use class `p-1 rounded-full`.

![image](https://user-images.githubusercontent.com/18244409/187033551-ed568071-ac21-4cca-b7de-40a0662070d8.png)

Tailwindplay: https://play.tailwindcss.com/34c1R1uABN

**Comment by sschoger** [comment]
Hey!

Good catch — this should be more optically centred now 👍🏻

<img width="196" alt="CleanShot 2022-08-30 at 12 58 20@2x" src="https://user-images.githubusercontent.com/2652515/187496037-ead1032d-5b43-48b7-a957-7d3fe399ef5e.png">

You can check out the Play here:
https://play.tailwindcss.com/OtmJ3fhKdT
