### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by Priyanshu88** [tailwindlabs/heroicons#777]
error - Error: You're trying to import `@heroicons/react/outline/SearchIcon` from Heroicons v1 but have installed Heroicons v2. Install `@heroicons/react@v1` to resolve this error.

**Comment by jyrkidn** [comment]
You'll have to add the size in your import (`import { SearchIcon } from '@heroicons/react/24/outline'`).

As you can read here: https://github.com/tailwindlabs/heroicons#react

**Comment by adamwathan** [comment]
Please read the error it explains everything.
