### ISSUE TITLE
Refresh Icon lost with the new version

### ISSUE THREAD

**Issue by bde-maze** [tailwindlabs/heroicons#781]
Hello there,

Some icons seem to be missing with the new update, like the Refresh one.
Do you plan to re implement old ones?

Thank you for the great work thought!

**Comment by EvertonWingert** [comment]
arrow-path

**Comment by RobinMalfait** [comment]
Hey! Thank you for your question!
Much appreciated! 🙏

As @EvertonWingert mentioned it is now called `arrow-path`.
