### ISSUE TITLE
ShieldExclamationTriangleIcon.js file does not exist

### ISSUE THREAD

**Issue by PeteAtkins** [tailwindlabs/heroicons#792]
Version 2.0.10
// export { default as ShieldExclamationTriangleIcon } from './ShieldExclamationTriangleIcon.js'
The above line is failing when importing either '@heroicons/vue/24/solid' or '@heroicons/vue/24/outline' as the files do not exist.
Commenting out the line in
node_modules/@heroicons/vue/24/outline/esm/index.js
and
node_modules/@heroicons/vue/24/solid/esm/index.js
resolves the issue temporarily

**Comment by adamwathan** [comment]
Hmm I can't find any reference to `ShieldExclamationTriangleIcon` anywhere in the codebase — here's the file you are talking about and there is no export with that name in there:

https://unpkg.com/browse/@heroicons/vue@2.0.10/24/outline/esm/index.js

Can you provide a reproduction project?

**Comment by adamwathan** [comment]
Weird one! Okay going to close then, thanks 👍
