### ISSUE TITLE
renamed 'exclamation' icon missing in v2 release notes

### ISSUE THREAD

**Issue by guischdi** [tailwindlabs/heroicons#808]
The new name `exclamation-triangle` (old name: `exclamation`) is missing in the mapping table in the [v2 release notes](https://github.com/tailwindlabs/heroicons/releases/tag/v2.0.0)

Please add that mapping.

**Comment by sschoger** [comment]
Hey! 

Thanks for catching this. Just updated the [release notes](https://github.com/tailwindlabs/heroicons/releases/tag/v2.0.0) to include this 👍🏻
