### ISSUE TITLE
Unaligned position of "i" in "information-circle" mini 20x20 icon

### ISSUE THREAD

**Issue by MrEmelianenko** [tailwindlabs/heroicons#828]
Hi,

I just noticed that "i" isn't centred correctly in the "information-circle" mini 20x20 icon.

Here are some screenshots:

<img width="140" alt="CleanShot 2022-09-24 at 11 14 41@2x" src="https://user-images.githubusercontent.com/678665/192105710-55227181-6245-489e-b13b-65797b28433e.png">
<img width="365" alt="CleanShot 2022-09-24 at 11 14 20@2x" src="https://user-images.githubusercontent.com/678665/192105712-ef75ac54-dd9a-4d35-bb7b-aa3402c7f9f9.png">

As you can see, the width of the blue square is 6px, while the width of the yellow square is 7px. I think we get this problem because of an uneven number of pixels, but could it be fixed somehow? Because IMHO, it looks a bit bad in UI:

<img width="482" alt="CleanShot 2022-09-24 at 11 19 09@2x" src="https://user-images.githubusercontent.com/678665/192105841-45b07641-202c-4be1-9727-198f1aaa5d71.png">

Have a good day,
Andrew

**Comment by adamwathan** [comment]
Yeah good catch agree this probably should be tweaked. I'll let Steve do the real one but I whipped together a tweaked version here if you want to try it:

https://play.tailwindcss.com/pffD6hY4JM

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

@sschoger fixed this for us, and it is available in the latest release!

You can try it using:
- `npm install heroicons@latest`.
- `npm install @heroicons/react@latest`.
- `npm install @heroicons/vue@latest`.
