### ISSUE TITLE
Error in release notes for 2.0

### ISSUE THREAD

**Issue by fribergr** [tailwindlabs/heroicons#833]
Hi,

When trying to follow the release notes for updating to Heroicons 2.0 for Vue we encountered a problem with the example.

The current example looks like this:
```
# Using React
npm install @heroicons/react@latest

# Using Vue
npm install @heroicons/vue/@latest
```

This is correct for react, but for vue you have a trailing slash, which does not work correctly. Should be:
```
npm install @heroicons/vue@latest
```

Best regards,
Robin

**Comment by RobinMalfait** [comment]
Hey! Thank you for your bug report!
Much appreciated! 🙏

This has been fixed!
