### ISSUE TITLE
Copy JSX button copies SVG

### ISSUE THREAD

**Issue by thelamina** [tailwindlabs/heroicons#840]
Hey, 

I noticed the button `Copy JSX` does not copy the actual JSX element but copies the SVG element instead.

Cheers.

**Comment by adamwathan** [comment]
Hey! It copies the SVG as JSX, which is the intended behavior. You’ll notice it’s using className, strokeWidth, etc, which are the changes needed to use the icon as inline JSX.

**Comment by ericvanular** [comment]
Thanks for the clarification. Currently, it's necessary to go hunt down the exact React component name at https://unpkg.com/browse/@heroicons/react@2.0.12, which feels clunky (unless I'm missing an easier way)

**Comment by adamwathan** [comment]
The React icon name is just the PascalCase version of the icon name you see on the site 👍🏻

So academic-cap is AcademicCap for example.
