### ISSUE TITLE
Fill colour on Academic Cap icon - Outline set.

### ISSUE THREAD

**Issue by claytsm** [tailwindlabs/heroicons#849]
Using Laravel Nova with a custom Menu and Icon.

For ref:

```
MenuSection::make('Education', [
       MenuItem::resource(OnlineCourse::class),
])->icon('academic-cap')->collapsable(),
```

Rendered icon has a fill colour in both shapes making up the Academic Cap.

<img width="156" alt="Screenshot 2022-10-07 at 12 05 38" src="https://user-images.githubusercontent.com/16179868/194540341-0fdf317a-e0f0-4771-a064-5244ac89b5ba.png">

**Comment by thecrypticace** [comment]
The latest versions in both v2 and v1 do not have a fill color for the academic cap in the outline style — while in Laravel Nova the embedded version does. I'll open an issue over there.
