### ISSUE TITLE
[Bug] Module "@heroicons/react/24/outline" has no exported member 'ChevronUpDownIcon'

### ISSUE THREAD

**Issue by podenborg** [tailwindlabs/heroicons#850]
I'm trying to use the `ChevronUpDownIcon` in v2.0.0 (formerly known as the `SelectorIcon` in v1.0.6), but when I try to import the icon into my React app I get a Typescript error that the icon is not exported from the `@heroicons/react/24/outline` module. 

I get the same error when trying to import the icon from `@heroicons/react/24/solid`.

This is the only icon I've seen this issue with so far. I believe it might be an issue with the package.

## Steps to Reproduce

- Initialize a new React application
- Install `@heroicons/react@2.0.0`
- Try to import the `ChevronUpDownIcon` in your app

**Comment by thecrypticace** [comment]
This is because you need to install the latest version of v2. The ChevronUpDownIcon was added back in v2.0.3. I recommend using the `latest` tag in NPM which will use a update your package.json to the latest version, use a semver caret, and install it (`npm install @heroicons/react@latest`).
