### ISSUE TITLE
Make it possible to change the stroke

### ISSUE THREAD

**Issue by devmanbr** [tailwindlabs/heroicons#855]
Please prioritize this.
### Discussed in https://github.com/tailwindlabs/heroicons/discussions/854

<div type='discussions-op-text'>

<sup>Originally posted by **devmanbr** October 11, 2022</sup>
Currently, in Heroicons's React library, the stroke of the outline version of icons is a fixed value of 1.5px. But that's not always what we need. I needed to increase that a little bit, and I had a lot of work to do to do that.

Please allow this change to be made through the component properties, simply passing the `stroke` prop with the desired value, for example:
```jsx
<AcademicCap stroke={2.5} />
```
</div>

**Comment by adamwathan** [comment]
Let's keep this in the original discussion, we issues specifically for bugs not feature requests 👍
