### ISSUE TITLE
No PencilAltIcon on vue heroicon

### ISSUE THREAD

**Issue by eskiesirius** [tailwindlabs/heroicons#860]
I have this error
```Uncaught (in promise) SyntaxError: The requested module '/node_modules/.vite/deps/@heroicons_vue_20_solid.js?v=bc2e7e64' does not provide an export named 'PencilAltIcon'```

`@heroicons/vue: 2.0.12`

**Comment by adamwathan** [comment]
Yeah there's no icon with that name, just `Pencil`, and `PencilSquare`:

<img width="893" alt="image" src="https://user-images.githubusercontent.com/4323180/195982074-38c4bc39-593a-40bb-8ac2-4fe38f0b91bd.png">

Heroicons v2.0 has some breaking changes like this one, see the release notes for information about migrating from v1 to v2: https://github.com/tailwindlabs/heroicons/releases/tag/v2.0.0

**Comment by eskiesirius** [comment]
@adamwathan thank you for this.. i was checking the icons here https://vue-hero-icons.netlify.app/
