### ISSUE TITLE
Vue typescript support

### ISSUE THREAD

**Issue by PhelixOchieng** [tailwindlabs/heroicons#863]
This is a follow up for issue #64.  I'm opening a new one because typescript support is only support for `@heroicons/react` and not `@heroicons/vue`.  I feel it would be nice to add the type definition for `@heroicons/vue`

**Comment by matthieu-alc** [comment]
Hello @PhelixOchieng I see you closed this as completed.
Unfortunately it seems like i still doesn't have typescript support for @heroicons/vue in my project.
Do you have a solution?

**Comment by ezmemoar** [comment]
Hope this one is noticed ASAP

**Comment by vpratfr** [comment]
I may have missed it in the docs, but how do we do it in practice?
