### ISSUE TITLE
Typescript issue: Cannot find module '@heroicons/react/20/solid' or its corresponding type declarations

### ISSUE THREAD

**Issue by Shaker-Pelcro** [tailwindlabs/heroicons#886]
I'm using the latest version (2.0.13).
Typescript version is (4.6.4)

I'm using and example from "TailwindUI" premium library, and it gives me this error ...
`Cannot find module '@heroicons/react/20/solid' or its corresponding type declarations`

And this is how I'm importing the icon ...
```javascript
import { ExclamationCircleIcon } from "@heroicons/react/20/solid";
```

This is breaking my app.
![image](https://user-images.githubusercontent.com/106151230/204215129-ebcd8478-de57-4f7f-af56-1c3bfee7c279.png)

**Comment by reinink** [comment]
Hey! Sorry, not sure what's up here. I just gave this a try myself in a fresh Next.js TypeScript app, and it's working:

<img width="994" alt="image" src="https://user-images.githubusercontent.com/882133/204819254-0406a22e-5819-41a3-b5ff-eca2bc9f58f2.png">

I am able to view the types for this icon in `./node_modules/@heroicons/react/20/solid/ExclamationCircleIcon.d.ts`.

I'm going to close this issue — but please feel free to open a new issue with a minimal reproduction that I can test with, and I'd be happy to have another look 👍

**Comment by kalnode** [comment]
I encountered a similar issue, found a solution:

**Legacy project (always worked):**
`"@heroicons/vue": "^1.0.6"`
`import { ChevronDownIcon, ChevronUpIcon } from '@heroicons/vue/outline'`

**New project (got error):**
I started with current version, but same import statement. Error occurred similar to OP.
`"@heroicons/vue": "^2.1.1"`
`import { ChevronDownIcon, ChevronUpIcon } from '@heroicons/vue/outline'`

**Works - Changing import statement:**
`import { ChevronDownIcon, ChevronUpIcon } from '@heroicons/vue/24/outline'`
