### ISSUE TITLE
New Outline Icons Issues

### ISSUE THREAD

**Issue by jsmith** [tailwindlabs/heroicons#90]
Love these new icons :) But some of the outline ones seem to have some unexpected shape/colors?

## Example
**From Twitter**
![Screen Shot 2020-08-06 at 5 32 35 PM](https://user-images.githubusercontent.com/18077531/89579836-d4390280-d80a-11ea-9e18-24349d3fbba2.png)

**GitHub Preview**
![Screen Shot 2020-08-06 at 5 31 51 PM](https://user-images.githubusercontent.com/18077531/89579772-b9668e00-d80a-11ea-996b-e744281a67ab.png)

## Full List
- [outline/backspace.svg](https://github.com/tailwindlabs/heroicons/blob/ecfba30b87166c07993ed8162ce47073752e41f9/outline/backspace.svg)
- [outline/calculator.svg](https://github.com/tailwindlabs/heroicons/blob/ecfba30b87166c07993ed8162ce47073752e41f9/outline/calculator.svg)
- [outline/cube.svg](https://github.com/tailwindlabs/heroicons/blob/ecfba30b87166c07993ed8162ce47073752e41f9/outline/cube.svg)
- [outline/truck.svg](https://github.com/tailwindlabs/heroicons/blob/ecfba30b87166c07993ed8162ce47073752e41f9/outline/truck.svg)
- [outline/variable.svg](https://github.com/tailwindlabs/heroicons/blob/ecfba30b87166c07993ed8162ce47073752e41f9/outline/variable.svg)
- [outline/document-search.svg](https://github.com/tailwindlabs/heroicons/blob/ecfba30b87166c07993ed8162ce47073752e41f9/outline/document-search.svg)
- [outline/finger-print.svg](https://github.com/tailwindlabs/heroicons/blob/ecfba30b87166c07993ed8162ce47073752e41f9/outline/finger-print.svg)
- [outline/folder-open.svg](https://github.com/tailwindlabs/heroicons/blob/ecfba30b87166c07993ed8162ce47073752e41f9/outline/folder-open.svg)
- [outline/presentation-chart-line.svg](https://github.com/tailwindlabs/heroicons/blob/ecfba30b87166c07993ed8162ce47073752e41f9/outline/presentation-chart-line.svg)
- [outline/search-circle.svg](https://github.com/tailwindlabs/heroicons/blob/ecfba30b87166c07993ed8162ce47073752e41f9/outline/search-circle.svg)
- [outline/status-offline.svg](https://github.com/tailwindlabs/heroicons/blob/ecfba30b87166c07993ed8162ce47073752e41f9/outline/status-offline.svg)
- [outline/wifi.svg](https://github.com/tailwindlabs/heroicons/blob/ecfba30b87166c07993ed8162ce47073752e41f9/outline/wifi.svg)

Thank you!

**Comment by matschik** [comment]
I can confirm. You can see a preview of all icons issues: https://vue-hero-icons.netlify.app
Even some solid icons.

**Comment by adamwathan** [comment]
Looks like these were somehow exported with fills, probably an issue that happened when exporting from Figma. Will raise with Steve this morning 👍

**Comment by codex-zaydek** [comment]
I wanted to add that in addition to @jsmith’s list, I noticed:

- `outline/academic-cap.svg`
- `outline/folder-open.svg`

Suffer from the same problem. In addition: `solid/login.svg` is missing entirely. I’m omitting all of these from the current release of https://heroicons.dev so as to not confuse users. When these are fixed I’ll update the site!

**Comment by matschik** [comment]
Color issue on `solid/arrows-expand.svg`

**Comment by sschoger** [comment]
Fixed outline issue and added solid login icon 👍
