### ISSUE TITLE
[Bugs] Currently broken icons

### ISSUE THREAD

**Issue by zaydek** [tailwindlabs/heroicons#93]
Hey @sschoger, I’ve been working with your icons extremely closely as I’ve been heavily investing in https://heroicons.dev. Based on your current commit ([82f6a4d](https://github.com/tailwindlabs/heroicons/commit/82f6a4d82bac701402da82eca57b2f2b9037c914)), these appear to be the broken icons:

```
outline/academic cap
outline/arrows-expand
outline/truck
solid/arrows-expand
solid/fire
solid/folder-add
solid/folder-download
solid/folder-remove
solid/shopping-bag
```

There may be more but this is what I caught and fixed in https://heroicons.dev and the Figma file to go along with it. I’d prefer to import your mastered versions of the icons, so I’ll be happy to swap them if you can get around to this.

If you look at the source for those icons, you’ll see what I mean. Some of them are simple fixes (just colors that need to be removed), and some of them are corrupted. Also, `solid/arrows-expand` has the wrong viewport; it should be `20 20` but it looks like it’s `19 20`.

Hope this helps!

**Comment by codex-zaydek** [comment]
FWIW I also sent you edit privileges for https://www.figma.com/file/vfjBXrSSOCgmVEX5fdvV4L (only I have edit priviledes right now — I’m happy to make you the owner of the file going forwards). If you are planning on doing more with Figma and Heroicons, I’d recommend using that link because of a lot of people are already relying on it.If you click. A lot of people are relying on the URL.

**Comment by model2020** [comment]
I need help

**Comment by deebov** [comment]
hey @codex-zaydek, I also noticed some [broken icons](https://twitter.com/deebovv/status/1294269838110662657)

**Comment by codex-zaydek** [comment]
@deebov Heroicons as-is doesn’t export to Figma 100% for whatever reason. I actually don’t know why. 🤷‍♂️

That’s why I added the Figma file to https://heroicons.dev (https://www.figma.com/file/vfjBXrSSOCgmVEX5fdvV4L). I cleaned up the bugs in these icons (without tampering with the icons themselves) so Figma users don’t get tripped up over this. Sorry about that!

**Comment by markcharles211** [comment]
hotmail
