### ISSUE TITLE
Share Icon

### ISSUE THREAD

**Issue by nico-heinrich** [tailwindlabs/heroicons#938]
Dear heros,

first of all, I love and use your icons — thanks for creating and sharing them!

Now, I use your share icon in my app and I felt the need to move it .1rem to the left. Is there a reason why it is so off to the right?

Cheers,

Nico

**Comment by williamd5** [comment]
It looks well aligned to me.

![image](https://user-images.githubusercontent.com/66572326/221109183-49f8b0fa-61ac-4867-8445-b64c8bc78126.png)

**Comment by reinink** [comment]
@nico-heinrich Hey! Glad you're enjoying Heroicons! 🤙

I just took a look at this icon, and it appears to be centered properly in all three versions:

<img width="834" alt="image" src="https://user-images.githubusercontent.com/882133/222420840-c61987a1-553e-4b27-bff7-8130efae1dd5.png">

Here's what it looks like in Figma:

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/882133/222421037-9d0db283-c5d8-45f0-a088-500dc145d06f.png">

So I suspect this must just be something to do with your particular implementation.

Hope that helps!

**Comment by williamd5** [comment]
> Thanks for the kind response!
> 
> ![image](https://user-images.githubusercontent.com/91636134/222424562-f6710a98-8b69-4e99-8361-540a48c9734f.png)
> 
> You are right, the fact that I use it with fully rounded corners makes it look off. While the share icon _is_ centered perfectly, it doesn't _look_ centered because it is way "heavier" on the right. I now simply use a transform on the icon in this case.
> 
> Cheers,
> 
> Nico

adding more padding and/or using a smaller icon can also reduce this effect/illusion
