### ISSUE TITLE
Type mismatch when used as Vue dynamic component

### ISSUE THREAD

**Issue by AndreKR** [tailwindlabs/heroicons#963]
In the (paid) [Tailwind UI sidebar layout](https://tailwindui.com/components/application-ui/application-shells/sidebar) the icons are used as [Vue dynamic components](https://vuejs.org/guide/essentials/component-basics.html#dynamic-components) like this:

```vue
<template>
  <a v-for="item in navigation">
    <div><component :is="item.icon" /> {{ item.name }}</div>
  </a>
</template>

<script setup lang="ts">
  import { HomeIcon } from '@heroicons/vue/24/outline';
  
  let navigation = [
    {icon: HomeIcon, name: 'Home'}
  ];
</script>
```

In PhpStorm (which I believe just passes through the TypeScript errors) the tag `<component :is="item.icon" />` causes an inspection error:

> Type FunctionalComponent<HTMLAttributes & VNodeProps> is not assignable to type string | ComponentDefinition
> Type FunctionalComponent<HTMLAttributes & VNodeProps> is not assignable to type ComponentConstructor
> Type FunctionalComponent<HTMLAttributes & VNodeProps> is not assignable to type ComponentDefinition 

Note that the Type `FunctionalComponent<HTMLAttributes & VNodeProps>` was inferred automatically, I did not specify an explicit type. (I don't know what's the type of `HomeIcon` is supposed to be.)

**Comment by reinink** [comment]
Hey! Can you share a minimal reproduction of this as a repo? It's really hard to reproduce this issue without one. Thanks!

**Comment by AndreKR** [comment]
https://github.com/AndreKR/heroicons-issue-963

To reproduce:
* Run `yarn install`
* Open in PhpStorm
* Wait for indexing
* Navigate to `src/App.vue`
* Note the instpection error in line 3

![image](https://user-images.githubusercontent.com/1188538/228973673-8a224274-4b11-40fb-94f1-18db8f6a4c18.png)

Now, the way I set up the repro, it can also run `tsc`. To do so, you can run `yarn run check`. However, the error does not appear then, so it might just as well be an error with PhpStorms type inferrence. I don't know enough about TypeScript to analyze what those types mean exactly.

**Comment by little3201** [comment]
same question for me

**Comment by thecrypticace** [comment]
This is a problem with PHPStorm's Vue plugin. It ships type definitions for HTML elements and they are referencing types that don't exist (or are outdated).

I discovered this by peering into the PHPStorm app bundle, locating the Vue JS plugin, and extracting the types from it (the plugin is a `.jar` which is just a specially-treated zip file). The types for `<component>` appear to be nearly identical in Vue 2 and Vue 3 according to PHPStorm.

Here's where I looked (at least on macOS) — you'll see here that I extracted the contents of the `.jar` file to make the screenshot easier to follow:
<img width="1243" alt="Screenshot 2023-05-11 at 16 16 39" src="https://github.com/tailwindlabs/heroicons/assets/614993/60bb5ede-33fb-4546-85c6-1fc82e609bf2">

Here's screenshots for the v3 (and v2 for reference) types:
<img width="1459" alt="Screenshot 2023-05-11 at 16 15 12" src="https://github.com/tailwindlabs/heroicons/assets/614993/ff6f6bd5-0e93-4773-898f-4b9e63762fc5">
<img width="1484" alt="Screenshot 2023-05-11 at 16 15 05" src="https://github.com/tailwindlabs/heroicons/assets/614993/fd7fc11d-9882-4ca6-ac31-9405025ada5b">

However Vue 3 does not export a type called `ComponentDefinition`:
<img width="669" alt="Screenshot 2023-05-11 at 16 23 55" src="https://github.com/tailwindlabs/heroicons/assets/614993/62bd2294-30d4-4ecb-a25d-fa166af17c40">

Vue 3 technically did, at one time, have a `ComponentConstructor<This>` type. However, this type was only internal and not exported and [it disappeared in 2019-ish](https://github.com/vuejs/core/commit/3cded86b98d1cf8eb3626747a72b53415e3a5c3d).

Now, it could be that `ComponentDefinition` is a PHPStorm-specific thing. But, in that case, the definition is incorrect as even a component created with `defineComponent` fails ([and the component does work as expected](https://play.vuejs.org/#eNpdjkEKgzAQRa/yySYKUvc2BkpXXfQG2RQ7YkCTYEahiHdvgqWUbgZm+P/N28QlhNO6kGiEYprC+GDSxgHqaVetOj8F78gxGhtbI+6vW+edEai1qnPCOFX/9NIau9kGRiReQrrYBJgZG4YKT+qto+uXuaOf/QQjkoAR51wfiXE8QfufL7YshgPdoCjR6s8cCplsZAXJFFmWlXF7md0Om+Qh9jermE+P)):

<img width="508" alt="Screenshot 2023-05-11 at 16 32 49" src="https://github.com/tailwindlabs/heroicons/assets/614993/714878c1-983e-4f08-a85b-d0b03939337d">

All in all, this is a PHPStorm issue with its own internal Vue types. Hope that helps. ✨
