### ISSUE TITLE
Stroke width broken again

### ISSUE THREAD

**Issue by sgoodluck** [tailwindlabs/heroicons#967]
It seems that strokewidth may be broken again?

Relevant issue #241 

Is anyone else experiencing this?

**Comment by reinink** [comment]
Hey! Reading your comment in the other issue, I can see you're trying to do this:

```jsx
import { ChevronRightIcon } from '@heroicons/react/24/solid';

<ChevronRightIcon className="h-4 w-4 stroke-[4px]" />
```

However that won't work for our "solid" set, as they don't use lines but rather solid shapes. That said, you can do this with our "outline" set:

```jsx
import { ChevronRightIcon } from '@heroicons/react/24/outline';

<ChevronRightIcon className="h-4 w-4 stroke-[4px]" />
```

Hope that helps 👍

**Comment by sgoodluck** [comment]
Incredibly helpful thank you! 
Created a minor documentation PR so that is stated in the readme! 

https://github.com/tailwindlabs/heroicons/pull/969
