### ISSUE TITLE
Can't copy icon JSX in heroicons.com

### ISSUE THREAD

**Issue by codigoisaac** [tailwindlabs/heroicons#986]
When I click "Copy JSX" in the icon at the icon library, what is actualy copied is the SVG. 

Clicking "Copy SVG" or "Copy JSX" gives the same result.

**Comment by adamwathan** [comment]
Hey! See previous discussions, it _is_ JSX but what we've chosen to do here is maybe not what you expect:

https://github.com/tailwindlabs/heroicons/issues/888

**Comment by thecrypticace** [comment]
Hey! It appears to be working for me. Can you provide more details about what you're seeing and what you're expecting?

**Comment by dibyendu02** [comment]
I don't think this issue have resolved faced the same issue
